---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: NetApp は、 Keystone STaaS サービスのすべてのリリースで、新機能と強化された機能を提供します。 
---
= Keystone STaaSの新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Keystone STaaS サービスの最新機能と拡張機能について学びます。



== 2025年11月10日

NetApp ConsoleのKeystoneダッシュボードの新しい機能強化:



=== 補償通知ボックスを入力してください

*監視*ページの*アラート モニター*タブには、カバレッジ ギャップが存在する場合に表示される*カバレッジの完了*通知ボックスが含まれています。このボックスには、容量または有効期限モニターが不足しているサブスクリプションと、サブスクリプションのないモニターがリストされます。ギャップに対処するには、既存のモニターにサブスクリプションを追加したり、新しいモニターを作成したり、使用されていないモニターを削除したりします。詳細については、 link:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html#manage-coverage-gaps["アラートモニターのカバレッジギャップを管理する"]。



== 2025年10月13日

NetApp ConsoleのKeystoneダッシュボードの新しい機能強化:



=== 資産タブの QoS ポリシーオーバーライド列

*アセット* タブ内の *クラスター内のボリューム* タブに、バックアップ ボリュームとミラー ボリュームに対して QoS ルールがバイパスされるかどうかを示す *QoS ポリシー オーバーライド* 列が追加され、*true* (ルールは無視)、*false* (ルールは適用)、または *N/A* (ミラー ボリュームの場合) が表示されます。


NOTE: Keystone v3 サブスクリプションの場合、QoS ポリシーは v3 オファリングには適用されないため、この列には *N/A* が表示されます。



=== 概要ページでのアラートの可視性が向上

*概要* ページに、*重大度別の未解決アラート* と *最も古い未解決Keystoneアラート* という 2 つの新しいアラート セクションが含まれるようになりました。詳細については、link:https://docs.netapp.com/us-en/keystone-staas/integrations/keystone-console.html["NetAppコンソールのKeystoneダッシュボード"] 。



== 2025年10月6日



=== BlueXPはNetAppコンソールになりました

NetAppコンソールは、強化され再構築されたBlueXP基盤上に構築され、オンプレミスとクラウド環境全体にわたるエンタープライズ グレードのNetAppストレージとNetAppデータ サービスの集中管理を提供し、リアルタイムの分析情報、ワークフローの高速化、および高度なセキュリティとコンプライアンスを備えた簡素化された管理を実現します。

変更内容の詳細については、link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetAppコンソールのリリースノート"^] 。



== 2025年9月22日



=== アラート監視の追加

BlueXPのKeystoneダッシュボードには、サブスクリプション全体のアラートとモニターを管理するための *監視* タブが追加されました。この新しいタブでは次のことが可能になります。

* 容量使用状況とサブスクリプションの有効期限に関するシステム生成アラートとユーザー定義アラートの両方を含むアクティブなアラートを表示して解決します。
* 容量使用状況とサブスクリプション有効期限イベントを追跡するためのアラート モニターを作成します。


詳細については、link:https://docs.netapp.com/us-en/keystone-staas-2/integrations/monitoring-alerts.html["アラートとモニターの表示と管理"] 。



=== 合理化されたパフォーマンス サービス レベルの表示

パフォーマンス サービス レベル情報は、別のタブから展開可能なビューに移動され、[*サブスクリプション*] タブ内で表示できます。各サブスクリプションの有効期限を表示するには、「*有効期限*」列の横にある下矢印をクリックします。詳細については、link:https://docs.netapp.com/us-en/keystone-staas-2/integrations/subscriptions-tab.html["Keystoneサブスクリプションの詳細を表示する"] 。



== 2025年8月28日



=== 新しい列による論理使用状況の追跡の強化

FabricPoolボリュームのKeystone消費量追跡を強化するために、新しい列「合計フットプリント」が追加されました。

* * BlueXPのKeystoneダッシュボード *: *Assets* タブ内の *Volumes in clusters* タブに *Total footnotes* 列が表示されます。
* *Digital Advisor*: * ボリュームとオブジェクト * タブ内の * ボリュームの詳細 * タブに * 合計フットプリント * 列が表示されます。


この列には、パフォーマンス層とコールド層の両方のデータを含む、 FabricPool階層化を使用したボリュームの合計論理フットプリントが表示されるため、 Keystone の消費量を正確に計算できます。



== 2025年8月5日



=== インスタンスレベルの消費データを表示する

BlueXPのKeystoneダッシュボードを通じて、各パフォーマンス サービス レベル インスタンスの現在の消費量と履歴データを表示できます。この機能は、 Keystoneバージョン 3 (v3) サブスクリプションをお持ちの場合、複数のインスタンスのパフォーマンス サービス レベルで利用できます。詳細については、link:https://docs.netapp.com/us-en/keystone-staas/integrations/current-usage-tab.html["Keystoneサブスクリプションの消費量を表示する"] 。



== 2025年6月30日



=== Keystoneバージョン 3 (v3) リリース

NetApp Keystone STaaS オファリングの最新リリースであるKeystoneバージョン 3 (v3) をサブスクライブできるようになりました。このバージョンでは、簡素化されたパフォーマンス サービス レベル、追加のバースト容量オプション、柔軟な課金頻度など、いくつかの機能強化が導入されています。これらの改善により、ストレージ ソリューションの管理、最適化、スケーリングが簡素化されます。詳細については、link:https://docs.netapp.com/us-en/keystone-staas/concepts/metrics.html["v3 のKeystone STaaS サービス"] 。

Keystoneバージョン 3 (v3) をサブスクライブするには、 Keystoneサポート チームにお問い合わせください。詳細については、link:https://docs.netapp.com/us-en/keystone-staas/concepts/gssc.html["Keystoneのサポートを受ける"] 。



== 2025年6月19日



=== BlueXPのKeystoneダッシュボード

BlueXPから直接Keystoneダッシュボードにアクセスできるようになりました。この統合により、すべてのKeystoneサブスクリプションとその他のNetAppサービスを 1 か所で監視、管理、追跡できるようになります。

BlueXPのKeystoneダッシュボードを使用すると、次のことが可能になります。

* すべてのサブスクリプションの詳細、容量の使用状況、資産を 1 か所で表示します。
* サブスクリプションを簡単に管理し、ニーズの変化に応じて変更をリクエストできます。
* ストレージ環境の最新情報を常に把握してください。


開始するには、 BlueXP の左側のナビゲーション メニューで *ストレージ > Keystone * に移動します。詳細については、link:https://docs.netapp.com/us-en/keystone-staas/integrations/dashboard-overview.html["Keystoneダッシュボードの概要"] 。



== 2025年1月8日



=== 毎日の累積データ使用量の表示オプションの追加

請求データを表示するバーをクリックすると、月次または四半期の請求期間における毎日の累積バースト データ使用量をグラフまたは表の形式で表示できるようになりました。詳細については、link:./integrations/consumption-tab.html#view-daily-accrued-burst-data-usage["毎日の累積バーストデータ使用量を表示する"] 。



== 2024年12月12日



=== 論理使用列の名前を変更しました

*ボリュームとオブジェクト* 内の *ボリュームの詳細* タブの *論理使用* 列の名前が * Keystone論理使用* に変更されました。



=== 拡張アセットタブ

* Keystoneサブスクリプション* 画面の *資産* タブに、* ONTAP* と * StorageGRID* という 2 つの新しいサブタブが追加されました。これらのサブタブには、サブスクリプションに基づいて、 ONTAPの詳細なクラスター レベルの分析情報とStorageGRIDのグリッド レベルの情報が提供されます。詳細については、link:./integrations/assets-tab.html["資産タブ"^] 。



=== 新しい列の表示/非表示オプション

*ボリュームとオブジェクト*内の*ボリュームの詳細*タブに、*列の非表示/表示*オプションが追加されました。このオプションを使用すると、列を選択または選択解除して、好みに応じてボリュームの表形式のリストをカスタマイズできます。詳細については、link:./integrations/volumes-objects-tab.html["ボリュームとオブジェクトタブ"^] 。



== 2024年11月21日



=== 拡張された請求書未払いバースト

四半期ごとの請求期間を選択した場合は、*請求済み累積バースト* オプションを使用して、四半期ごとに累積バースト使用量データを表示できるようになりました。詳細については、link:./integrations/consumption-tab.html#view-accrued-burst["請求済みの未払いバーストを表示"^] 。



=== ボリューム詳細タブの新しい列

論理使用量の計算の明確さを向上させるために、[ボリュームとオブジェクト] タブ内の [ボリュームの詳細] タブに 2 つの新しい列が追加されました。

* *論理 AFS*: ボリュームのアクティブ ファイル システムによって使用されている論理容量を表示します。
* *物理スナップショット*: スナップショットによって使用される物理スペースを表示します。


これらの列により、ボリュームのアクティブ ファイル システムによって使用されている論理容量とスナップショットによって使用されている物理スペースの合計を示す *Logical Used* 列がより明確になります。



== 2024年11月11日



=== 強化されたレポート生成

Digital Advisorのレポート機能を使用して、 Keystoneデータの詳細を表示する統合レポートを生成できるようになりました。詳細については、link:./integrations/options.html#generate-consolidated-report-from-digital-advisor["統合レポートを生成する"^] 。



== 2024年7月10日



=== ラベルの変更

ラベル *現在の使用量* が *現在の消費量* に変更され、 *容量の傾向* が *消費量の傾向* に変更されます。



=== サブスクリプションの検索バー

* Keystoneサブスクリプション* 画面内のすべてのタブの *サブスクリプション* ドロップダウンに検索バーが追加されました。  *サブスクリプション*ドロップダウンにリストされている特定のサブスクリプションを検索できます。



== 2024年6月27日



=== サブスクリプションの一貫した表示

* Keystoneサブスクリプション* 画面が更新され、選択したサブスクリプション番号がすべてのタブに表示されます。

* * Keystoneサブスクリプション* 画面内の任意のタブが更新されると、画面は自動的に *サブスクリプション* タブに移動し、すべてのタブが *サブスクリプション* ドロップダウンにリストされている最初のサブスクリプションにリセットされます。
* 選択したサブスクリプションがパフォーマンス メトリックにサブスクライブされていない場合は、[パフォーマンス] タブに、ナビゲーション時に [サブスクリプション] ドロップダウンにリストされている最初のサブスクリプションが表示されます。




== 2024年5月29日



=== 強化されたバーストインジケーター

使用状況グラフ インデックスの *バースト* インジケーターが強化され、バースト制限のパーセンテージ値が表示されるようになりました。この値は、サブスクリプションの合意されたバースト制限に応じて変化します。  *使用状況*列の*バースト使用量*インジケーターにマウスを合わせると、*サブスクリプション*タブでバースト制限値を確認することもできます。



=== サービスレベルの追加

サービス レベル *CVO Primary* および *CVO Secondary* は、コミット容量がゼロの料金プランを持つサブスクリプション、またはメトロ クラスターで構成されたサブスクリプションに対してCloud Volumes ONTAP をサポートするために含まれています。

* これらのサービス レベルの容量使用状況グラフは、* Keystoneサブスクリプション* ウィジェットの古いダッシュボードと *容量傾向* タブから表示できます。また、*現在の使用状況* タブから詳細な使用状況情報も表示できます。
* *サブスクリプション*タブでは、これらのサービスレベルは次のように表示されます。 `CVO (v2)` *使用タイプ*列で、これらのサービス レベルに応じて課金を識別できるようになります。




=== 短時間のバーストのためのズームイン機能

*容量トレンド*タブには、使用状況チャートの短期バーストの詳細を表示するためのズームイン機能が追加されました。詳細については、以下を参照してください。 link:./integrations/consumption-tab.html["容量トレンドタブ"^] 。



=== サブスクリプションの表示強化

サブスクリプションのデフォルトの表示が強化され、追跡 ID で並べ替えられるようになりました。  *サブスクリプション* タブのサブスクリプション (*サブスクリプション* ドロップダウンと CSV レポートを含む) は、トラッキング ID のアルファベット順 (a、A、b、B の順) に基づいて表示されるようになります。



=== 蓄積バースト表示の強化

*容量トレンド* タブの容量使用率の棒グラフにマウスを移動したときに表示されるツールヒントに、コミットされた容量に基づいて発生したバーストの種類が表示されるようになりました。暫定発生バーストと請求済み発生バーストを区別し、コミット容量がゼロの料金プランのサブスクリプションの場合は *暫定発生消費量* と *請求済み発生消費量* を表示し、コミット容量がゼロ以外のサブスクリプションの場合は *暫定発生バースト* と *請求済み発生バースト* を表示します。



== 2024年5月9日



=== CSVレポートの新しい列

*容量トレンド* タブの CSV レポートに、詳細を向上させるために *サブスクリプション番号* 列と *アカウント名* 列が含まれるようになりました。



=== 拡張使用タイプ列

*サブスクリプション* タブ内の *使用タイプ* 列が拡張され、ファイルとオブジェクトの両方のサービス レベルをカバーするサブスクリプションの論理使用状況と物理使用状況がコンマ区切りの値として表示されるようになりました。



=== ボリューム詳細タブからオブジェクトストレージの詳細にアクセスします

*ボリュームとオブジェクト* タブ内の *ボリュームの詳細* タブには、ファイルとオブジェクトの両方のサービス レベルを含むサブスクリプションのボリューム情報とともに、オブジェクト ストレージの詳細が表示されるようになりました。詳細を表示するには、「ボリュームの詳細」タブ内の「オブジェクト ストレージの詳細」ボタンをクリックします。



== 2024年3月28日



=== ボリューム詳細タブの QoS ポリシーコンプライアンス表示の改善

*ボリュームとオブジェクト* タブ内の *ボリュームの詳細* タブでは、サービス品質 (QoS) ポリシーのコンプライアンスがより明確に表示されるようになりました。以前は *AQoS* と呼ばれていた列の名前が *Compliant* に変更され、QoS ポリシーが準拠しているかどうかが示されます。さらに、ポリシーが固定か適応型かを指定する新しい列「QoS ポリシー タイプ」が追加されました。どちらにも該当しない場合は、列に「_利用不可_」と表示されます。詳細については、以下を参照してください。 link:./integrations/volumes-objects-tab.html["ボリュームとオブジェクトタブ"^] 。



=== ボリューム概要タブに新しい列と簡素化されたサブスクリプション表示を追加しました

* *ボリュームとオブジェクト* タブ内の *ボリュームの概要* タブに、*保護済み* という新しい列が追加されました。この列には、サブスクライブしたサービス レベルに関連付けられている保護されたボリュームの数が表示されます。保護されているボリュームの数をクリックすると、「ボリュームの詳細」タブに移動し、保護されているボリュームのフィルタリングされたリストを表示できます。
* *ボリューム サマリー* タブが更新され、アドオン サービスを除いた基本サブスクリプションのみが表示されるようになりました。詳細については、以下を参照してください。 link:./integrations/volumes-objects-tab.html["ボリュームとオブジェクトタブ"^] 。




=== キャパシティトレンドタブの累積バースト詳細表示に変更

*容量トレンド*タブの容量使用率の棒グラフにマウスを移動したときに表示されるツールヒントには、当月の累積バーストの詳細が表示されます。過去数か月分の詳細は入手できません。



=== Keystoneサブスクリプションの履歴データを表示するためのアクセスが強化されました

Keystoneサブスクリプションが変更または更新された場合に、履歴データを表示できるようになりました。サブスクリプションの開始日を以前の日付に設定して、以下を表示できます。

* *容量傾向*タブからの消費量と累積バースト使用量データ。
* *パフォーマンス* タブからのONTAPボリュームのパフォーマンス メトリック。


データは、サブスクリプションの選択した開始日に基づいて表示されます。



== 2024年2月29日



=== 資産タブの追加

* Keystoneサブスクリプション* 画面に *資産* タブが追加されました。この新しいタブには、サブスクリプションに基づいてクラスター レベルの情報が提供されます。詳細については、以下を参照してください。 link:./integrations/assets-tab.html["資産タブ"^] 。



=== ボリュームとオブジェクトタブの改善

ONTAPシステム ボリュームをより明確にするために、*ボリューム* タブに *ボリューム サマリー* と *ボリューム詳細* の 2 つの新しいタブ ボタンが追加されました。  *ボリューム サマリー* タブには、サブスクライブしたサービス レベルに関連付けられているボリュームの総数 (AQoS コンプライアンス ステータスや容量情報など) が表示されます。 *ボリュームの詳細*タブには、すべてのボリュームとその詳細が一覧表示されます。詳細については、以下を参照してください。 link:./integrations/volumes-objects-tab.html["ボリュームとオブジェクトタブ"^] 。



=== Digital Advisorでの検索エクスペリエンスの強化

* Digital Advisor* 画面の検索パラメータに、 Keystoneサブスクリプション番号とKeystoneサブスクリプション用に作成されたウォッチリストが含まれるようになりました。サブスクリプション番号またはウォッチリスト名の最初の 3 文字を入力できます。詳細については、以下を参照してください。 link:./integrations/keystone-aiq.html["Active IQ Digital AdvisorでKeystoneダッシュボードを表示する"^] 。



=== 消費データのタイムスタンプを表示する

* Keystoneサブスクリプション* ウィジェットの古いダッシュボードで、消費データのタイムスタンプ (UTC) を表示できます。



== 2024年2月13日



=== プライマリサブスクリプションにリンクされたサブスクリプションを表示する機能

一部のプライマリ サブスクリプションには、リンクされたセカンダリ サブスクリプションを設定できます。その場合、プライマリサブスクリプション番号は引き続き *サブスクリプション番号* 列に表示されますが、リンクされたサブスクリプション番号は *サブスクリプション* タブの新しい列 *リンクされたサブスクリプション* に表示されます。  *リンクされたサブスクリプション* 列は、リンクされたサブスクリプションがある場合にのみ使用可能になり、それらについて通知する情報メッセージが表示されます。



== 2024年1月11日



=== 発生したバーストに対して返された請求データ

*キャパシティトレンド*タブで、*Accrued Burst*のラベルが*Invoiced Accrued Burst*に変更されました。このオプションを選択すると、課金された累積バースト データの月次チャートを表示できます。詳細については、以下を参照してください。 link:./integrations/consumption-tab.html#view-accrued-burst["請求済みの未払いバーストを表示"^] 。



=== 特定の料金プランの累積消費量の詳細

コミット容量が _ゼロ_ の料金プランがあるサブスクリプションがある場合は、[容量の傾向] タブで累積消費量の詳細を表示できます。  *請求済み未払い消費量*オプションを選択すると、請求済み未払い消費量データの月次チャートを表示できます。



== 2023年12月15日



=== ウォッチリストによる検索機能

Digital AdvisorのウォッチリストのサポートがKeystoneシステムまで拡張されました。ウォッチリストで検索することで、複数の顧客のサブスクリプションの詳細を表示できるようになりました。  Keystone STaaSでのウォッチリストの使用に関する詳細については、以下を参照してください。link:./integrations/keystone-aiq.html#search-by-keystone-watchlists["Keystoneウォッチリストで検索"^] 。



=== UTCタイムゾーンに変換された日付

Digital Advisorの * Keystoneサブスクリプション* 画面のタブに返されるデータは、UTC 時間 (サーバータイムゾーン) で表示されます。クエリの日付を入力すると、自動的に UTC 時間として扱われます。詳細については、以下を参照してください。 link:./integrations/keystone-aiq.html["Keystoneサブスクリプションダッシュボードとレポート"^] 。
