---
sidebar: sidebar 
permalink: concepts/components.html 
keywords: infrastructure component, deployment requirement, installation requirement 
summary: ご使用の環境でNetApp Keystone STaaS サービスを有効にするために必要なコンポーネントについて説明します。 
---
= 展開に必要なコンポーネント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ご使用の環境でNetApp Keystone STaaS サービスを有効にするには、いくつかのコンポーネントが必要です。始める前に、これらのコンポーネントの詳細を確認する必要があります。



== サイト要件

スペース、ラック、PDU、電源、冷却などのサイト固有の要件がいくつかあり、ここでは追加のネットワークおよびセキュリティ要件について説明します。



=== スペース

Keystoneインフラストラクチャ機器を収容する床面積 (顧客が提供)。  NetApp は、最終的な構成に基づいて重量仕様を提供します。



=== ラック

顧客が操作するオファリングの 4 つのポスト ラック (顧客が用意)。  NetAppが運営するサービスでは、要件に応じてNetAppまたは顧客がラックを提供できます。  NetApp は42 個のディープ ラックを提供します。



=== PDU

十分な数の C13 コンセントを備えた 2 つの個別の保護された回路に接続された配電ユニット (PDU) を用意する必要があります。顧客が運営するサービスでは、C19 コンセントが必要になる場合があります。  NetAppが運営するサービスでは、要件に応じてNetAppまたは顧客が PDU を提供できます。



=== 電力

必要な電力を供給する必要があります。 NetApp は、最終的な構成に基づいて、200 V 定格 (標準 A、最大 A、標準 W、最大 W、電源コードの種類と数量) に基づく電力要件仕様を提供します。すべてのコンポーネントには冗長電源が備わっています。  NetApp はキャビネット内の電源コードを提供します。



=== 冷却装置

NetApp は、最終的な構成と要件に基づいて、冷却要件の仕様 (標準 BTU、最大 BTU) を提供できます。



=== 仮想マシン

Keystone Collector および ITOM Collector の展開には仮想マシンが必要です。インストールの前提条件については、link:../installation/installation-overview.html["Keystone Collector のインストールガイド"]そしてlink:../installation/itom-prereqs.html["ITOM Collectorのインストール要件"]。その他の要件は展開中に共有されます。



=== 導入オプション

Keystone Collector は次の方法で導入できます。

* VMware OVA テンプレート (VMware vCenter Server 6.7 以降が必要)
* お客様は、Debian 12、Red Hat Enterprise Linux 8.6 以降の 8.x バージョン、または CentOS 7 (既存の環境のみ) のいずれかのオペレーティング システムで実行される Linux サーバーを提供します。  Keystoneソフトウェアは、 `.deb`または `.rpm`Linux ディストリビューションに応じてパッケージが異なります。


ITOM Collector は次の方法で展開できます。

* お客様は、Debian 12、Ubuntu 20.04 LTS、Red Hat Enterprise Linux (RHEL) 8.x、Amazon Linux 2023、またはそれ以降のバージョンで実行される Linux サーバーを提供します。
* 顧客は、Windows Server 2016 以降のバージョンを実行する Windows サーバーを提供します。
+

TIP: 推奨されるオペレーティング システムは、Debian 12、Windows Server 2016、またはそれ以降のバージョンです。





=== ネットワーク

Keystone Collector および AIOps ソリューション ゲートウェイの運用と保守に不可欠なソフトウェアの更新と使用状況データのアップロードには、_keystone.netapp.com_ への送信アクセスが必要です。

顧客の要件と使用されるストレージ コントローラに応じて、 NetApp は顧客サイトで 10 GB、40 GB、および 100 GB の接続を提供できます。

NetApp は、 NetAppが提供するインフラストラクチャ デバイスにのみ必要なトランシーバーを提供します。お客様のデバイスに必要なトランシーバーと、 NetAppが提供するKeystoneインフラストラクチャ デバイスへのケーブルを用意する必要があります。



== リモートアクセス要件

顧客のデータ センターまたは顧客所有の共同設置サービスにインストールされたストレージ インフラストラクチャとKeystone運用センターとの間には、ネットワーク接続が必要です。コンピューティング、仮想マシン、およびインターネット サービスを提供するのは顧客の責任です。お客様は、OS パッチ適用 (OVA ベース以外の展開) と社内セキュリティ ポリシーに基づくセキュリティ強化についても責任を負います。ネットワーク設計は安全なプロトコル上で行われる必要があり、ファイアウォール ポリシーはNetAppと顧客の両方によって承認されます。

NetApp は、 Keystone の顧客に監視や課金などのサービスを提供するために、監視と管理のためにインストールされたハードウェアおよびソフトウェア コンポーネントにアクセスする必要があります。最も一般的な方法は、顧客ネットワークへの仮想プライベート ネットワーク (VPN) 接続を確立し、必要なデータにアクセスすることです。新しいサービスに対してファイアウォール ポートを開くことで生じると顧客が感じる運用上の複雑さを克服するために、監視ツールは外部接続を開始します。 ITOM 監視ソリューションや Zuora などのNetAppクラウド アプリケーションは、この接続を使用してそれぞれのサービスを実行します。この方法は、このサービスの一部である監視コンポーネントへのアクセスを提供しながら、ファイアウォール ポートを開かないという顧客要件を満たします。
