---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability, v2, version 2 
summary: NetApp Keystone STaaS サービスでは、メトリックを測定するためにいくつかの用語を使用します。サービスのバージョン 2 でKeystoneを使用する際には、これらの用語について詳しく理解しておく必要があります。 
---
= Keystoneで使用される指標と定義
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS サービスでは、メトリックを測定するためにいくつかの用語を使用します。  Keystoneを使用する際には、これらの用語についてさらに詳しく知る必要があるかもしれません。

Keystone STaaS サービスでは、メトリックを測定するために次の用語と定義が使用されます。

* 容量: GiB、TiB、PiB で測定されます。
* IO 密度: IOPS/TiB: ワークロードによって消費されている合計スペースに基づいて、1 秒あたりに処理される入出力操作の数 (テビバイト単位)。
* サービスの可用性
* 正確なデータアクセスの耐久性
* レイテンシと速度




== メトリクス測定

* *GiB、TiB、PiB での容量測定*: 1024 を基数としたデータ ストレージ容量の測定 (1 GiB = 1024^3^ バイト、1 TiB = 1024^4^ バイト、1 PiB = 1024^5^ バイト)。
* *IOPS/TiB での操作カウンター チャート*: アプリケーションによって要求された 1 秒あたりのプロトコル操作数を、ワークロードで使用されるボリュームのサイズで割ったもの。
* *可用性*: サービスによって正常に応答された I/O 要求の数を、サービスに対して行われた I/O 要求の合計数で割ったパーセンテージとして測定されます。これは 1 か月のサービス境界で測定され、顧客が提供する施設、ネットワーク、その他のサービスの予定されたサービス停止時間や利用不可時間は含まれません。
* *耐久性*: 顧客による削除や破損を除き、忠実度の損失なしにアクセスされたデータの割合。
* *レイテンシ*: サービス境界 (ストレージ コントローラーの I/O ポート) で測定された、クライアントから受信した I/O 要求を処理する時間。




=== スループットパフォーマンスメトリック

スループット パフォーマンス メトリックは、次の基準に基づいてファイル サービスとブロック サービスにのみ適用されます。

* 32 KBのブロックサイズ
* IO比率は読み取り70% / 書き込み30%




=== IO密度の変化

IOPS/TiB および/または MBps/TiB で計算される IO 密度は、次の要因によって異なります。

* ワークロードの特性
* 以下を除くレイテンシ:
+
** アプリケーションのレイテンシ
** ホストのレイテンシ
** コントローラポートとの間でデータを転送する際の顧客ネットワークの遅延
** FabricPoolの場合、オブジェクト ストアへのデータ転送に関連するオーバーヘッド遅延
** IOをサービスレベルの最大値内に維持するためにQoSによって自動的に適用される遅延


* 使用済み容量の一部としてカウントされるユーザーおよびスナップショットコピーデータ
* ボリューム内のデータ量に関係なく、各ONTAPボリュームに割り当てられた絶対最小 IOPS。
+
** エクストリーム：1,000 IOPS
** プレミアム: 500 IOPS
** パフォーマンス、標準、価値: 75 IOPS


* Advanced Data Protection アドオン サービスを使用している場合、ターゲット レイテンシはローカル ストレージからの IO 要求の処理にのみ適用されます。




=== ボリュームAQoS

各ONTAPボリュームには、適切な適応型サービス品質 (AQoS) ポリシーが適用されている必要があります。それ以外の場合、AQoS ポリシーが適用されていない各ボリューム内の容量は、最高のサービス レベルの料金で課金されます。
