---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: クローンボリューム、高度なデータ保護など、特定の構成に対するKeystone の課金について説明します。 
---
= Keystone請求のさまざまなシナリオ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
特定の構成におけるKeystone の課金について理解すると、サービスの使用を最適化し、コストを管理するのに役立ちます。構成には、クローンボリューム、高度なデータ保護、一時ボリューム、QoS ポリシー、 SnapMirror の宛先、LUN、システム/ルート ボリュームが含まれます。



== クローンボリュームの課金

ONTAPでボリュームのクローンを作成し、それをデータのバックアップと復元に使用する場合、追加料金なしでクローンを引き続き使用できます。ただし、クローンボリュームを長期間にわたってビジネスの他の目的に使用する場合は料金が発生します。

次の点に注意してください。

* クローン ボリュームのサイズが親ボリュームの 10% 未満 (クローン ボリュームで使用される物理容量と親ボリュームで使用される物理容量の比較) である限り、クローン ボリュームは課金されません。
* クローンボリュームには 24 時間の猶予期間はありません。クローンのサイズのみが考慮されます。
* クローン ボリュームが親の物理サイズの 10% を超えると、クローンには標準ボリューム (論理使用容量) として課金されます。




== 高度なデータ保護の請求

高度なデータ保護では、 NetApp MetroClusterを使用して、物理的に分離された 2 つのクラスター間でデータをミラーリングします。  MetroClusterミラーリングされたアグリゲートの場合、データは各クラスタに 1 回ずつ、合計 2 回書き込まれます。 Keystoneサービスは、それぞれの側で個別に消費量を課金するため、同一の消費量記録が 2 つ生成されます。アドオン料金は、データがソースにあるか、ミラーリングされたデータかミラーリングされていないデータかに関係なく、サブスクリプション内のすべての容量に適用されます。

ONTAP System Manager（System Manager）またはActive IQ Unified Manager （Unified Manager）を使用してクラスターを監視する場合、これらのツールで報告される消費量とKeystoneの間に矛盾が生じることがあります。  System Manager と Unified Manager はミラー化された (リモート) クラスタ上のボリュームを報告せず、その際にKeystoneサービスが報告する消費メトリックの半分を報告します。

.例：
サイト A とサイト B はMetroCluster構成でセットアップされています。ユーザーがサイト A に 10 TB のボリュームを作成すると、サイト B にも同一の 10 TB のボリュームが作成されます。Keystoneは各サイトで 10 TB の消費量を識別し、合計で 20 TB の増加となります。  System Manager と Unified Manager は、サイト A に 10 TB のボリュームが作成されたことを報告しますが、サイト B に 10 TB のボリュームが作成されたことを報告しません。

さらに、高度なデータ保護を備えたKeystoneシステムで作成されたすべてのボリュームは、ボリュームがミラーリングされているかどうかに関係なく、高度なデータ保護の消費量としてカウントされます。



== 一時ボリュームの請求

場合によっては、ボリュームを移動するときに、 ONTAPによって一時 (TMP) ボリュームが作成されることがあります。これらの一時ボリュームは存続期間が短く、これらのボリュームの消費量は課金対象として測定されません。



== 課金と適応型QoSポリシー

Keystone はサービス レベルに基づいて消費量を測定します。各サービス レベルは、特定の適応型サービス品質 (QoS) ポリシーに関連付けられています。展開中に、サブスクライブしたKeystoneサービスの各適応型 QoS ポリシーの詳細が通知されます。ストレージ管理操作中は、予期しない課金を回避するために、サブスクライブしたサービス レベルに応じてボリュームに適切なアダプティブ QoS ポリシーが割り当てられていることを確認してください。  ONTAPのアダプティブQoSポリシーの詳細については、以下を参照してください。link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["QoSによるスループットの保証 - 概要"^] 。



== SnapMirror の宛先に対する課金

SnapMirror宛先ボリュームの価格は、ソースに割り当てられたサービス レベルの適応型 QoS ポリシーによって決まります。ただし、送信元に関連付けられた適応型 QoS ポリシーがない場合、宛先は利用可能な最低のサービス レベルに基づいて課金されます。



== LUNの課金

LUN の場合、アダプティブ QoS ポリシーによって管理されるボリュームと同じ課金パターンが適用されます。  LUN に個別のアダプティブ QoS ポリシーが設定されている場合は、次のようになります。

* LUN のサイズは、その LUN に関連付けられたサービス レベルに応じて消費量としてカウントされます。
* ボリューム内の残りのスペース（ある場合）は、ボリュームに設定されたサービス レベルのアダプティブ QoS ポリシーに従って課金されます。




== システムボリュームとルートボリューム

システム ボリュームとルート ボリュームは、 Keystoneサービスの全体的な監視の一部として監視されますが、カウントも課金もされません。これらのボリュームの消費は課金の対象外となります。
