---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS は、事前に定義されたサービス レベルでストレージ容量を提供します。  Keystoneによって管理される各ボリュームは、サービス レベルに関連付けられています。 
---
= Keystoneのパフォーマンスサービスレベル
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS は、事前に定義されたパフォーマンス サービス レベルでデータ ストレージ容量を提供します。  Keystoneサービスによって管理される各ボリュームには、パフォーマンス サービス レベルが関連付けられています。

サブスクリプションには複数の料金プランがあり、各料金プランはパフォーマンス サービス レベルに対応しています。各料金プランには、パフォーマンス サービス レベルごとにコミットされた容量があります。

各パフォーマンス サービス レベルは、I/O 密度 (IOPS/TiB/ボリューム) によって定義されます。これは、パフォーマンス (1 秒あたりの入出力操作数 [IOPS]) と使用済みストレージ容量 (TiB) の比率であり、ボリュームあたりの平均レイテンシにおける IOPS/TiB です。

ストレージ環境、ストレージおよび消費のニーズに基づいて、パフォーマンス サービス レベルを選択します。基本パフォーマンス サービス レベルはデフォルトで利用できます。アドオン サービスを選択した場合は、特定のパフォーマンス サービス レベルも追加で利用できます。たとえば、高度なデータ保護アドオン サービスの場合、サブスクリプションには _Advanced Data-Protect_ パフォーマンス サービス レベルが割り当てられます。


TIP: NetApp Keystone STaaSパフォーマンスサービスレベルの詳細なサービス説明は入手可能です。 https://www.netapp.com/services/keystone/terms-and-conditions/["ここをクリックしてください。"^] 。

サポートされているストレージ タイプ (ファイル、ブロック、オブジェクト、クラウド サービス) の基本パフォーマンス サービス レベルについては、次のセクションで説明します。



== ファイルおよびブロックストレージのパフォーマンス サービス レベル

*サポートされているプロトコル*: NFS、CIFS、iSCSI、FC

|===


| *パフォーマンスサービスレベル* | *過激* | *プレミアム* | *パフォーマンス* | *標準* | *価値* 


| *サンプルワークロードの種類* | 分析、データベース、ミッションクリティカルなアプリ | VDI、VSI、ソフトウェア開発 | OLTP、OLAP、コンテナ、ソフトウェア開発 | ファイル共有、ウェブサーバー | バックアップ 


| *ボリュームあたりに保存される最大 IOPS/論理 TiB* | 12,288 | 4,096 | 2,048 | 512 | 128 


| *ボリュームあたりに割り当てられる最大 IOPS/論理 TiB* | 6,144 | 2,048 | 1,024 | 256 | 64 


| *ボリュームあたり最大 MBps/論理 TiB 保存数（32K B/S 時）* | 384 | 128 | 64 | 16 | 4 


| *目標90パーセンタイルレイテンシ* | <1ミリ秒 | <2ミリ秒 | 4ミリ秒未満 | 4ミリ秒未満 | <17ミリ秒 


| *ブロックサイズ* 5+| 32K 


| *コミット容量タイプと従量制容量タイプ* 5+| 論理 
|===


=== ファイルおよびブロックストレージのパフォーマンスサービスレベルの詳細

基本パフォーマンス サービス レベル メトリックは、次の条件によって異なります。

* ファイルおよびブロック ストレージのパフォーマンス サービス レベルは、 ONTAP 9.7 以降をサポートします。
* パフォーマンス サービス レベルの IOPS/TiB/ボリューム、MBps/TiB/ボリューム、およびレイテンシ値は、ボリュームに保存されるデータの量、32 KB のブロック サイズ、および 70% の読み取り IO 操作と 30% の書き込み IO 操作のランダムな組み合わせに基づいています。
* 実際の IOPS/TiB/ボリュームおよび MBps/TiB/ボリュームは、実際または想定されるブロック サイズ、システム ワークロードの同時実行性、または入出力操作によって異なる場合があります。
* レイテンシには以下は含まれません。
+
** アプリケーションまたはホストのレイテンシ
** コントローラポートとの間の顧客ネットワーク遅延
** FabricPoolの場合、オブジェクトストアへのデータ転送に関連するオーバーヘッド
** IO をパフォーマンス サービス レベルの最大値内に維持するために QoS によって自動的に適用される遅延


* レイテンシ値はMetroCluster書き込み操作には適用されません。これらの書き込み操作は、リモート システムの距離に依存します。
* ストレージ システム上の 1 つ以上のボリュームに AQoS ポリシーが割り当てられていない場合、これらのボリュームは非準拠ボリュームと見なされ、これらのシステムにはターゲット パフォーマンス サービス レベルは適用されません。
* _Expected IOPS_ は、階層化ポリシーが「なし」に設定され、クラウド内にブロックがない場合にのみFabricPoolを対象とします。  _予想 IOPS_ は、 SnapMirror同期関係にないボリュームを対象としています。
* ワークロード IO 操作は、 Keystone の順序に従って、展開されたすべてのコントローラー間で分散される必要があります。




== オブジェクト ストレージ

*サポートされているプロトコル*: S3

|===


| *パフォーマンスサービスレベル* | オブジェクト 


| *ワークロードの種類* | メディア リポジトリ、アーカイブ 


| *ボリュームあたりに保存される最大 IOPS/論理 TiB* | 該当なし 


| *ボリュームあたりに保存される最大 MBps/論理 TiB* | 該当なし 


| *平均レイテンシ* | 該当なし 


| *コミット容量タイプと従量制容量タイプ* | 物理 
|===

NOTE: FabricPoolストレージの場合、レイテンシにはオブジェクト ストアへのデータ転送に関連するオーバーヘッドは含まれません。



== クラウド ストレージ

*サポートされているプロトコル*: NFS、CIFS、iSCSI、S3 (AWS および Azure のみ)

|===


| *パフォーマンスサービスレベル* | Cloud Volumes ONTAP 


| *ワークロードの種類* | 災害復旧、ソフトウェア開発/テスト、ビジネスアプリ 


| *ボリュームあたりに保存される最大 IOPS/論理 TiB* | 該当なし 


| *ボリュームあたりに保存される最大 MBps/論理 TiB* | 該当なし 


| *平均レイテンシ* | 該当なし 
|===
[NOTE]
====
* コンピューティング、ストレージ、ネットワークなどのクラウド ネイティブ サービスは、クラウド プロバイダーによって請求されます。
* これらのサービスは、クラウド ストレージとコンピューティングの特性に依存します。


====
*関連情報*

* link:../concepts/supported-storage-capacity.html["サポートされているストレージ容量"]
* link:..//concepts/metrics.html["Keystoneサービスで使用されるメトリックと定義"]
* link:../concepts/qos.html["Keystoneのサービス品質 (QoS)"]
* link:../concepts/pricing.html["Keystone価格"]

