---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: NetApp Keystone STaaS サービス バージョン 2 でサポートされるストレージ容量の種類について説明します。 
---
= Keystoneでサポートされているストレージ容量
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS サービスは、いくつかの種類のストレージ容量をサポートしています。これらのさまざまな容量用語を理解しておくと、 Keystoneを使用するときに役立ちます。



== 論理容量

これは、顧客によってKeystoneインフラストラクチャに配置されたデータです。すべてのKeystone容量は論理容量を参照します。たとえば、1 TiB のファイルがKeystoneインフラストラクチャに保存される場合は、少なくとも 1 TiB の容量を購入する必要があります。



== コミット済み容量

サブスクリプション期間中に毎月課金される最小論理容量:

* 容量は各サービス レベルにコミットされます。
* 期間中にコミット容量と追加のサービス レベルを追加できます。




=== コミットされた容量の変更

サブスクリプションの期間中、コミットされた容量を変更できます。ただし、一定の前提条件があります。

* コミットされた容量は、特定の条件に基づいて削減される可能性があります。詳細については、link:../concepts/capacity-requirements.html["容量の縮小"] 。
* サブスクリプションがさらに 12 か月間更新されない限り、サブスクリプションの有効期限の 90 日前にはコミットされた容量を増やすことはできません。
* コミットされた容量の変更は、 BlueXPインターフェースまたはKeystone Success Manager (KSM) からリクエストできます。変更のリクエストについては、以下を参照してください。link:../concepts/gssc.html["NetApp Keystoneサポート"] 。




== 消費容量

消費容量とは、サービスで現在消費されている容量 (ストレージの TiB 単位) を指します。それは次の合計です:

* ユーザー データのすべてのインスタンスとタイプ (コピー、ミラー コピー、バージョンなど) を保存するために使用される論理容量。
* 元のボリュームのサイズの 10% を超えるクローン ボリュームを保存するために使用される論理容量。
* スナップショット コピーからの差分データを保存するために使用される物理容量。
* 割り当てられた物理容量。




== バースト容量

NetApp Keystoneサービスを使用すると、サービス レベルのコミットされた容量に加えて追加の容量を使用できます。これをバースト容量使用量と呼びます。

次の点に注意してください。

* バースト容量はKeystone契約で合意されています。通常、コミット容量の 20% 超に設定され、コミット容量と同じ料金で課金されます。
* バースト容量は弾力的に消費され、消費された平均量に応じて日単位で課金されます。




== 請求容量

月額料金 = (コミット容量 [TiB] * コミットレート [$/TiB]) + (1 日あたりの平均プロビジョニングバースト容量 [TiB] * バーストレート [$/TiB])。毎月の請求書には、コミットされた容量に基づいた最低料金が含まれます。

月額料金は、毎日の平均バースト容量消費量に基づいて最低料金を超えて変動します。
