---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: NetApp Keystone STaaS サービス バージョン 2 でサポートされるストレージ容量の種類について説明します。 
---
= Keystoneでサポートされているストレージ容量
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS サービスは、いくつかの種類のストレージ容量をサポートしています。これらのさまざまな容量用語を理解しておくと、 Keystoneを使用するときに役立ちます。



[[logical-capacity]]
== 論理容量

これは、ストレージアレイによって提供されるデータ効率化を適用する前の、ユーザーデータを保存するために必要なストレージ容量です。



[[committed-capacity]]
== コミット済み容量

サブスクリプション期間中に毎月課金される最小論理容量:

* 容量は各パフォーマンス サービス レベルに割り当てられます。
* 期間中にコミット容量と追加のサービス レベルを追加できます。




[[changes-to-committed-capacity]]
=== コミットされた容量の変更

サブスクリプションの期間中、コミットされた容量を変更できます。ただし、一定の前提条件があります。

* コミットされた容量は、特定の条件に基づいて削減される可能性があります。詳細については、link:../concepts/capacity-requirements.html["容量の縮小"] 。
* サブスクリプションがさらに 12 か月間更新されない限り、サブスクリプションの有効期限の 90 日前にはコミットされた容量を増やすことはできません。
* コミットされた容量の変更は、コンソールまたはKeystone Success Manager (KSM) からリクエストできます。変更のリクエストについては、以下を参照してください。 link:../concepts/support-services.html["NetApp Keystoneサポート"]。




[[consumed-capacity]]
== 消費容量

消費容量とは、サービス上で現在消費されているストレージ容量（TiB単位）を指します。データ保存タイプに基づいて計算方法が異なります：

* *統合ストレージまたはブロック最適化ストレージ*：消費容量は、注文プロセス中に選択された容量の種類（論理容量または物理容量）に基づいて計算されます。計算は、パフォーマンスサービスレベルのインスタンスごとに実行されます。
+
.. *論理容量*：以下の合計です。
+
*** ストレージアレイのデータ効率化前の、コピー、ミラーコピー、バージョン、クローンなど、すべてのインスタンスとタイプの顧客データを保存するための計測可能な論理容量。
*** スナップショットおよび特定のクローンのメタデータと差分データを保存するために使用される物理容量。
*** シックプロビジョニングされた物理容量。


.. *物理容量*：以下の合計です：
+
*** ストレージ アレイのデータ効率化後の、コピー、ミラー コピー、バージョン、クローンなど、お客様のデータのすべてのインスタンスとタイプを格納するための従量制物理容量。
*** スナップショットのメタデータと差分データを保存するために使用される物理容量。
*** シックプロビジョニングされた物理容量。




* *オブジェクトストレージ*：消費容量は、すべてのノードにわたるすべてのインスタンスとタイプの顧客データを保存するために使用される計測対象の物理容量として計算されます。この計算は、設定された情報ライフサイクル管理（ILM）ポリシーに基づいています。
* *Cloud Volumes ONTAP*：消費容量は、すべてのCloud Volumes ONTAPボリュームの計測済みプロビジョニング済み論理容量として計算されます。




[[burst-capacity]]
== バースト容量

NetApp Keystoneサービスを使用すると、サービス レベルのコミットされた容量に加えて追加の容量を使用できます。これをバースト容量使用量と呼びます。

次の点に注意してください。

* バースト容量はKeystone契約で合意されています。通常、コミット容量の 20% 超に設定され、コミット容量と同じ料金で課金されます。
* バースト容量は弾力的に消費され、消費された平均量に応じて日単位で課金されます。




[[billed-capacity]]
== 請求容量

月額料金 = (コミット容量 [TiB] * コミットレート [$/TiB]) + (1 日あたりの平均プロビジョニングバースト容量 [TiB] * バーストレート [$/TiB])。毎月の請求書には、コミットされた容量に基づいた最低料金が含まれます。

月額料金は、毎日の平均バースト容量消費量に基づいて最低料金を超えて変動します。
