---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: NetApp Keystone STaaS サービスの以前のリリースで見つかった問題は、以降のリリースで修正されています。 
---
= Keystone STaaS の問題を修正
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS サービスの以前のリリースで見つかった問題は、以降のリリースで修正されています。

[cols="3*"]
|===
| 問題の説明 | 修正後 | リリース 


 a| 
*Assets* タブでは、 StorageGRIDのアセットは表示されません。
 a| 
固定
 a| 
2025/06/19



 a| 
Advance Data-Protect サービス レベルの場合、[消費傾向] タブのグラフに、プライマリ サイトとミラー サイトの分割が表示されます。
 a| 
チャートにはプライマリ サイトとミラー サイトの分割が表示されなくなりました。
 a| 
2025/06/19



 a| 
Debian パッケージを使用してインストールされた既存のKeystone Collector が、 Keystone Collector 管理 TUI を介して HTTP プロキシを設定したり、Unified Manager を有効にしたりしようとすると、TUI が応答しなくなります。
 a| 
固定
 a| 
2025/05/19



 a| 
共通設定が欠落しているため、 Keystone Collector for StorageGRIDを正しく構成できません。
 a| 
固定
 a| 
2025/05/12



 a| 
Keystone Collector は、バージョン 9.11 より前のバージョンを実行しているONTAPクラスターの使用状況データを収集できません。
 a| 
固定
 a| 
2025/04/30



 a| 
リンクされたサブスクリプションの消費値に誤った負の数値が表示されるため、コミットされた使用量の合計が不正確に高く表示されます。
 a| 
固定
 a| 
2025/04/14



 a| 
いくつかのサブスクリプションのサービス レベルの履歴データを *消費傾向* タブで表示できません。
 a| 
固定
 a| 
2025/04/14



 a| 
Digital Advisorダッシュボードの *ウォッチリスト* に * Keystoneサブスクリプション* オプションが表示されず、*レポート* に *サブスクリプション番号* オプションが表示されません。
 a| 
固定
 a| 
2025/03/19



 a| 
Digital Advisorダッシュボードからウォッチリストを作成または変更した後、*ウォッチリスト* からいくつかのKeystoneサブスクリプションが消えてしまいます。
 a| 
固定
 a| 
2025/03/19



 a| 
有効期限が切れ、同じ追跡 ID だがサービス レベルが異なるサブスクリプションで更新された場合、そのサブスクリプションに関連付けられているサービス レベルの履歴データを *消費傾向* タブで表示できません。
 a| 
固定
 a| 
2025/03/19



 a| 
* Keystoneサブスクリプション* ページの *サブスクリプション* タブから 10 ～ 12 を超えるサブスクリプションを選択した場合、サブスクリプションのレポートを生成できません。
 a| 
固定
 a| 
2025/01/08



 a| 
*ボリュームとオブジェクト* タブの *ボリューム サマリー* サブタブが StorageGrid サブスクリプションの読み込みに失敗します。
 a| 
固定
 a| 
2024/11/21



 a| 
*消費傾向*タブに移動すると、日付範囲を選択するための*開始日*フィールドには、デフォルトで将来の日付が表示されます。
 a| 
固定
 a| 
2024/09/04



 a| 
AQoS ポリシーを設定すると、 Keystone Collector 管理 TUI が応答しなくなります。
 a| 
固定
 a| 
2024/08/07



 a| 
*容量傾向*タブの*容量傾向*オプションから、現在の日付に対応する日付が前月の開始日と終了日の両方として選択されている場合、使用状況チャートには、指定された 1 日の期間を超えたデータが表示されます。
 a| 
使用状況チャートに、指定された 1 日間の期間のデータが正しく表示されるようになりました。
 a| 
2024/06/27



 a| 
MetroCluster構成が設定されていないサブスクリプションの場合、*容量トレンド* タブ内の *CVO プライマリ* および *CVO セカンダリ* サービス レベルでは、履歴累積バースト データは利用できません。
 a| 
固定
 a| 
2024/06/21



 a| 
AutoSupportサブスクリプションの *ボリュームの詳細* タブにリストされるオブジェクト ストレージの消費値が正しく表示されません。
 a| 
オブジェクト ストレージの消費値が正しく表示されるようになりました。
 a| 
2024/06/21



 a| 
MetroCluster構成で設定されたAutoSupportサブスクリプションの *Assets* タブ内でクラスタ レベルの情報を表示できません。
 a| 
固定
 a| 
2024年6月21日



 a| 
*容量トレンド*タブから生成されたCSVレポートの*アカウント名*列に、カンマで区切られたアカウント名が含まれている場合、CSVレポートでKeystoneデータが誤って配置される `(,)`。
 a| 
Keystoneデータは CSV レポート内で正しく配置されます。
 a| 
2024/05/29



 a| 
消費量がコミットされた容量を下回っている場合でも、*容量トレンド*タブから累積バースト使用量を表示します。
 a| 
固定
 a| 
2024/05/29



 a| 
*容量トレンド*タブの*現在のバースト*インデックスアイコンのツールチップテキストが正しくありません。
 a| 
正しいツールチップ テキスト「_現在消費されているバースト容量の量。」を表示します。これは、選択した日付範囲ではなく、現在の請求期間のものであることに注意してください。
 a| 
2024/03/28



 a| 
Keystoneデータが 24 時間存在しない場合、AQoS 非準拠ボリュームおよびMetroClusterパートナーに関する情報は、 AutoSupportサブスクリプションでは利用できません。
 a| 
固定
 a| 
2024/03/28



 a| 
1 つのサービス レベルのみで AQoS 準拠を満たしているボリュームに 2 つのサービス レベルが割り当てられている場合、*ボリュームの概要* タブと *ボリュームの詳細* タブにリストされる AQoS 非準拠ボリュームの数が一致しないことがあります。
 a| 
固定
 a| 
2024/03/28



 a| 
AutoSupportサブスクリプションの *Assets* タブには情報が表示されません。
 a| 
固定
 a| 
2024/03/14



 a| 
階層化とオブジェクト ストレージの両方の料金プランが適用可能な環境でMetroClusterとFabricPool の両方が有効になっている場合、ミラー ボリューム (構成ボリュームとFabricPoolボリュームの両方) のサービス レベルが誤って導出される可能性があります。
 a| 
ミラーボリュームには適切なサービス レベルが適用されます。
 a| 
2024/02/29



 a| 
単一のサービス レベルまたは料金プランを持つ一部のサブスクリプションでは、*ボリューム* タブ レポートの CSV 出力に AQoS コンプライアンス列がありませんでした。
 a| 
コンプライアンス列はレポートに表示されます。
 a| 
2024/02/29



 a| 
一部のMetroCluster環境では、[パフォーマンス] タブの IOPS 密度チャートで異常が時々検出されました。これは、ボリュームとサービス レベルのマッピングが不正確であったために発生しました。
 a| 
グラフは正しく表示されます。
 a| 
2024/02/29



 a| 
バースト消費記録の使用状況インジケーターがオレンジ色で表示されていました。
 a| 
インジケーターが赤で表示されます。
 a| 
2023/12/13



 a| 
容量傾向、現在の使用状況、およびパフォーマンス タブの日付範囲とデータは、UTC タイムゾーンに変換されませんでした。
 a| 
すべてのタブのクエリとデータの日付範囲は、UTC 時間 (サーバータイムゾーン) で表示されます。タブの各日付フィールドには UTC タイムゾーンも表示されます。
 a| 
2023/12/13



 a| 
タブとダウンロードした CSV レポートの開始日と終了日が一致しませんでした。
 a| 
修理済み。
 a| 
2023/12/13

|===